### ISSUE TITLE
Improvement discussion

### ISSUE THREAD

**Issue by sivakornchong** [UBC-MDS/DSCI-532_2024_10_vanweather#51]

**Comment by sivakornchong** [comment]
Improvement discussions (app refinements):

- [x] 1. Data pipeline automation - Anu/ Oak
- [x] 2. Date range issue - Anu
- altair has an existing limit of 5000 rows. 
- Should be able to resolve by vegafusion.

- [x] 3. Blue point on altair - Katherine
- [x] 4. Adjust headings (currently too long) - Weilin
- [x] 5. Adjust the average value be not be fixed value - Weilin

Jo's feedback
- [x] 1. Update text in cards dynamically to say how many year and the values for that time period - (Milestone 4)
- [x] 2. Be able to show more data by using vegafusion - Anu
- [x] 3. Update data over time each time it is refreshed - Anu/ Oak
- [x] 4. Some separation to indicate which widgets are global and which are local. Pretty much only that the first row is only controlled by the date picker, which is not intuitive currently. -  (Milestone 4)

Minor:

- [x]  1. Points and line same color? -> Remove the blue points - Katherine
- [x]  2. Dropdown font is small -> We think it's ok
- [x]  3. Slightly smaller so no scrolling needed -> Ok, we will reduce height of 4 charts. - Weilin
- [x]  4. Padding withing cards? -> Ok
- [x]  5. Maybe smooth -> Change to tool tip -  Weilin
- [x]  6.  Center title? Padding under? Bg color -> Padding between the title and charts.  (Milestone 4)

Other tasks:

- [x] 1. Break code into multiple files - Oak

-> data extraction from .ipynb to .py3. |
-> data preprocessing relating functions in one file, layout-related functions in another file, and split the server side into as many files as makes sense to you based on your apps functionality.

- [x] 2. Reflection - Katherine

- [x] 3. Update readme page with latest animation

**Comment by czwcandy** [comment]
This discussion happened in Milestone3, and the points listed above are finished in Milestone 3 and Milestone 4. Thanks to people who give feedback to make our dashboard better.
