### ISSUE TITLE
Updating reports/m1_proposal.md

### ISSUE THREAD

**Issue by WeilinHan8** [UBC-MDS/DSCI-532_2024_10_vanweather#7]
The proposal should be written as a markdown document in your repo (`reports/m1_proposal.md`),
be max 1,000 words in length,
and include the following sections:

1. Motivation and purpose - Anu
2. Description of the data - Oak
3. Research questions - Katherine
4. App sketch and description - Weilin

**Comment by WeilinHan8** [comment]
Hi team, please refer to this [link](https://github.ubc.ca/MDS-2023-24/DSCI_532_milestone1_group10/blob/master/milestone1.md) for more detail about requirement for each section.

**Comment by sivakornchong** [comment]
I have split out the task for my side to assign speciffic github branch more easily.
For data, refer to #12
