### ISSUE TITLE
Feedback from paolocodina

### ISSUE THREAD

**Issue by paolocodina** [UBC-MDS/DSCI-532_2024_10_vanweather#70]
Good work! I only have some small suggestions for improvement.

### Larger points of feedback

- I find that the way the range feature is displayed could be better. I think the option to click and find the date should be kept, but also having a visual where you can drag the interval to a specific date would be helpful. I believe this is called a date slicer, and including it in your display would make the dashboard more interactive and visually appealing.

- The idea behind the app is good, and stakeholders should be able to use it well. I think making the filters look hierarchical would make interactions clearer. I noticed the date range and aggregation chart affect most visuals, but anything below that is specific to each chart, and a way to show this difference would be nice.

- I believe the shareholders will be satisfied with this dashboard. I am wondering if the shareholders would benefit if the apparent temperature change had an easy way to change from being related to the date to not being related to the date. So if we filtered the date, we could choose whether or not it is filtered along with the date.

- Overall, the visual is very nice, but I think experimenting with fonts could add to the whole visual.

### Smaller points of feedback

- I think the 'Load Data Frame' button could be made more visually appealing by changing the font or the general shape of the button.

- Some of the titles are simply the name of the y-axis with 'over time' added. Having more unique names could enhance the visual appeal.

- Including a brief description of the dashboard next to the title would make it easier for unfamiliar users to understand.

- Adding a small section to display the author's name would be beneficial.

- Adding more description to the readme could be beneficial to better understand the dash especially next to the GIF.

**Comment by sivakornchong** [comment]
Hi Paolo,

Thank you for your opinions. We have taken a look at the issues raised here and appreciate the comments. 
Larger points of feedback

I find that the way the range feature is displayed could be better. I think the option to click and find the date should be kept, but also having a visual where you can drag the interval to a specific date would be helpful. I believe this is called a date slicer, and including it in your display would make the dashboard more interactive and visually appealing.
- We make an aesthetic decision to keep the calendar.

The idea behind the app is good, and stakeholders should be able to use it well. I think making the filters look hierarchical would make interactions clearer. I noticed the date range and aggregation chart affect most visuals, but anything below that is specific to each chart, and a way to show this difference would be nice.
- We will take this feedback and implement it. 

I believe the shareholders will be satisfied with this dashboard. I am wondering if the shareholders would benefit if the apparent temperature change had an easy way to change from being related to the date to not being related to the date. So if we filtered the date, we could choose whether or not it is filtered along with the date.
- With respect to our intent, we will keep to the current configuration. 

Overall, the visual is very nice, but I think experimenting with fonts could add to the whole visual.
- With respect to our intent, we will keep to the aesthetic configuration. 

Smaller points of feedback
I think the 'Load Data Frame' button could be made more visually appealing by changing the font or the general shape of the button.
- We will take this comment and improve on the font shape. 

Some of the titles are simply the name of the y-axis with 'over time' added. Having more unique names could enhance the visual appeal.
- With respect to our intent, we will keep to the aesthetic configuration. 

Including a brief description of the dashboard next to the title would make it easier for unfamiliar users to understand.
- With respect to our intent, we will keep to the aesthetic configuration. There is insufficient space on the dashboard. We will put description in the readme file. 

Adding a small section to display the author's name would be beneficial.
- We will implement this too! 

Adding more description to the readme could be beneficial to better understand the dash especially next to the GIF.
- Same comment as Chris, we will do that. 

Thank you!

**Comment by czwcandy** [comment]
We updated our dashboard based on some feedbacks . For others, we don't plan to update after discussion according to reasons Oak commented.
