### ISSUE TITLE
Feedback from M4

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_10_vanweather#76]
Implement all minor

Major:

Minor:
- [x] Invert cards to be green background and white text font
- [x] Clearer about terms like "apparent temp" etc. Fix axis titles.
- [x] Style for reload button
- [x] Remove "Date" from x-axis
- [x] Make font in parenthesis smaller
- [x] Why is the date popup not close to the widget
- [x] Select only most important temperatures
- [x] Link to repo, names, at the bottom of the sidebar

**Comment by czwcandy** [comment]
Your suggestions are very helpful and we have made changes on our dashboard based on your all suggestion. Done! Thank you!
